sudo: required

services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_1ba1eb16049b_key -iv $encrypted_1ba1eb16049b_iv -in multi-k8s-kubeconfig.yaml.enc -out multi-k8s-kubeconfig.yaml -d
  - sudo apt-get update && sudo apt-get install -y apt-transport-https
  - curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  - echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
  - sudo apt-get update
  - sudo apt-get install -y kubectl
  - sudo snap install doctl
  - sudo snap connect doctl:kube-config
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t nickadamu/react-client-test -f ./client/Dockerfile.dev

env:
  global:
    - SHA=$(git rev-parse HEAD)


script:
  - docker run nickadamu/react-client-test npm test -- --coverage

deploy:
  provider : script
  script: bash ./deploy.sh
  on:
    branch: master
